plt.subplot(1, 2, 2)
# plt.plot(f2)
# plt.title("Fitness Values over Time")
# plt.xlabel("Iteration")
# plt.ylabel("Fitness")
# plt.plot(losss)
# plt.ylabel('Fitness')
# plt.xlabel("Iteration:")
# plt.show()